sudo: false
dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install codecov
  - python setup.py install
script:
  - python setup.py lint
  - coverage run setup.py test
after_success:
  - codecov
