sudo: false
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install pytest-cov codecov
  - python setup.py install
script:
  - python setup.py lint
  - pytest --cov
after_success:
  - codecov
